### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by richarddavenport** [flamelink/flamelink#1]
Hi! Looking forward to using Flamelink! Just curious if you have permissions figured out? If so, any documentation? If not, do you need any help?

**Comment by jperasmus** [comment]
Hi @richarddavenport,

Thanks for getting in contact. Can you elaborate a bit what you mean in terms of permissions?

**Comment by richarddavenport** [comment]
Certainly! Specifically the database rules: [https://firebase.google.com/docs/database/security/quickstart](https://firebase.google.com/docs/database/security/quickstart).

I'm currently using the default rules:
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

I love how flamelink gives you the cms and a simple sdk, but I'm curious if the construction of the rules are left to the developer to figure out, or if there are some rules that we should be using out of the box.

With the default rules, all it takes is for someone to "hack" the system is to be logged in. Someone that is logged in could basically delete or change everything.

I've built firebase apps that have not only rules, but also permissions built in. Just wondering how flamelink will be handling these concerns.

Thanks!

**Comment by phantompepper** [comment]
@richarddavenport I think adding a project walks you through what you're asking.

In the Firebase Console, for Database:
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
    "flamelink": {
      ".read": "auth != null",
      ".write": "auth != null"
    }
  }
}

```

and for Storage:

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
    match /flamelink/{allPaths=**} {
      allow read;
      allow write: if request.auth != null;
    }
  }
}
```

**Comment by richarddavenport** [comment]
@phantompepper Thanks, but the default rules are not secure enough. Does anyone on the flamelink team have a roadmap or even an idea as to what the rules will/should be? If not, I could certainly chime in and give my advice.

I've used firebase a ton and can tell you these rules do not hold up in a production environment. Unless the devs just really don't care about the data.

**Comment by jperasmus** [comment]
@richarddavenport Great! Thought for a moment you were talking about the Flamelink specific permissions/user groups that are used to determine which of your users can do what within the app. The Flamelink permissions will be added to the SDK before the official v1 release, which should be within the next month or so.

The Flamelink permissions are not DB level permissions like the ones you are talking about that you get with Firebase itself, but will be only code restricted.

With that said, I totally agree with what you are saying with the Firebase db rules. Flamelink aims to help developers and content managers to be an interface between them and Firebase, so it is still always highly recommended that the developers set the appropriate and strictests rules possible for their production environments. It obviously greatly depends on the type of application you are building and the type of data you are storing in your Firebase db. I would be very interested to hear your learnings and learn from your experience to see how we can help developers out.

@phantompepper Thank you for contributing to the discussion here 👍🏼 Those permissions that we recommend is for the developer to get going with Flamelink as quickly as possible, but we leave it up to the developer to further restrict as s/he sees fit for the app they're building, baring in mind that if you make it too strict for the Flamelink app to read and write to the db, the Flamelink app might not work.

What I normally suggest with write permissions is to only open it up for your actual users that you added to the CMS itself with a rule similar to this:

```
{
  "rules": {
    // your global rules here for anything outside of flamelink
    "flamelink": {
      ".read": "auth != null",
      ".write": "(auth.uid === someUID) || (auth.uid === anotherUID)"
    }
  }
}
```

"someUID" and "anotherUID" here obviously needs to be replaced with the actual Firebase user UIDs that you have given Flamelink access to.

With Firebase's ability to set nested rules, you can also go more fine grained and open up certain sections of your db to be read from anyone for non-sensitive data that you might be using on your app and then tie down other areas a lot more. As an example, I would restrict the `schemas` section more than for instance the `navigation` data, because you most likely would like to read and display your navigation in your app to everyone, but the schema only really is of use from within the Flamelink app.

After this discussion, I will make sure to add some more notes to the docs to make it better.

Looking forward to hear your thoughts!

**Comment by richarddavenport** [comment]
@jperasmus Awesome, that all sounds very reasonable. I jumped in head first when the beta was released and didn't even go through the getting started, just started clicking and typing like a monkey banging the keyboard. ¯\_(ツ)_/¯

**Comment by phantompepper** [comment]
@jperasmus Ah this makes sense! Thanks so much!  @richarddavenport I'm glad this was clarified by the team. I have no idea what I'm doing lol

**Comment by jperasmus** [comment]
haha, none of us knows what we're doing! That's the beauty of being developers! 👻

I'll make sure to add some more documentation to the SDK docs and eventually to the user docs as well, to make this very clear, perhaps with some "suggested/recommended" rules. The only problem with sometimes suggesting something is that some people will just copy it and assume it will work in all scenarios.

Are you guys happy with me closing this issue or do you want to add anything else?

**Comment by phantompepper** [comment]
@jperasmus Thanks! This definitely clarifies the subject for me anyway. Excited to dig further into this CMS!
