### ISSUE TITLE
All records are using integer and not string breaking firebase security rules

### ISSUE THREAD

**Issue by pieer** [flamelink/flamelink#12]
It's not possible at the moment to restrict access to some records because they are all save with integers.
From firebase doc: Path keys are always strings. For this reason, it's important to keep in mind that when we attempt to compare a $ variable to a number, this will always fail. This can be corrected by converting the number to a string (e.g. $key === newData.val()+'')

**Comment by jperasmus** [comment]
For anyone else that might stumble into a similar issue. The issue has been resolved on Slack. The problem is not so much the entry keys being strings or integers but the level at which we can set permissions for the SDK to read the data. The SDK can read and write content at the content type level or at the individual entry level, it can unfortunately not work with permissions for specific fields within the individual entry object. In other words, either the whole entry is readable or not, it cannot be partially readable.
