### ISSUE TITLE
Link to Docs in main CMS GUI Page

### ISSUE THREAD

**Issue by phantompepper** [flamelink/flamelink#13]
Hi! I’ve lately noticed how often I’m switching between the docs and the main Schema builder GUI ( flamelink.io) Would it be possible to add a quick link up top (ie the classic “?” ) to link to the API docs? Thanks!

**Comment by jperasmus** [comment]
Hi, that's a great idea. I've added it quickly, it should make it to production shortly (hopefully today, otherwise within the next day or two). Will look something like this:

<img width="242" alt="docs" src="https://user-images.githubusercontent.com/6787452/35848330-6f2c07d8-0b26-11e8-80e5-050440ed2bff.png">

**Comment by phantompepper** [comment]
PERFECT! Thanks!

**Comment by phantompepper** [comment]
Real quick - I notice it only appears in flamelink.io/dashboard. In flamelink.io/edit (after login) it goes away.

**Comment by jperasmus** [comment]
hi, yes, I noticed it after pushing it to production. It will be available in the next release. 👍

**Comment by phantompepper** [comment]
👌 thanks!
