### ISSUE TITLE
Flamelink CMS upload problem

### ISSUE THREAD

**Issue by stepanic** [flamelink/flamelink#14]
Hello,

this not the problem with this library, but I am not able to upload the file from your web application.

But this is the only place where I can publicly share the screenshot with you :)) it would be very nice to create the separate GitHub repository `flamelink/cms-support` or something like this.

Your web application looks very nice, but I got this error during upload, all other features for now works perfect:

![screen shot 2018-02-09 at 09 38 38](https://user-images.githubusercontent.com/315282/36018899-abf08686-0d7d-11e8-8f9e-642b7c6bb59f.png)

Best regards,
Matija Stepanic
CEO @ ITalk Ltd.

**Comment by jperasmus** [comment]
Hi Matija,

Thanks for taking the time to create this ticket and for the kind words. We've seen this issue a few times before with newly created Firebase projects. When you add the project to Flamelink, the URL for the Storage Bucket has not propagated yet. Luckily, the fix is very easy, you can simply remove the project from Flamelink and then add it again. This is safe to do because we do not touch the database but simply unlink. Your data stays intact.

Please let me know if this works for you. Feel free to also join our [Slack community](https://flamelink.io/slack) if you have any other issues or questions.

**Comment by stepanic** [comment]
Thank you, this workaround works :D
I guess that this bucket association implementation during project creating could be also added in the catch block of this error during upload and this will be fix which will cover any futures problems for new projects. 

Br,
MS

**Comment by jperasmus** [comment]
Yes, I'll make sure that we up the priority for this since we've seen it about 4 times now. Ideally, we can try and block the project from being added in the first place if the Storage Bucket URL hasn't propagated yet.
