### ISSUE TITLE
How to do basic calculations like percentage on flamelink ?

### ISSUE THREAD

**Issue by rakipinsight** [flamelink/flamelink#17]
I have 3 fields => Bill Amount, Tip Percentage & Tip Amount. How to calculate the Tip Percentage based on Bill Amount using the fields given in the Schema ?

**Comment by jperasmus** [comment]
From a purely content point of view, this seems more like an implementation detail of your mobile or web app that is consuming the data, so that the CMS can store the two amounts and the percentage being displayed by your app code.

If you really need to store the tip percentage in your database, you can set up a [Firebase Cloud Function](https://firebase.google.com/docs/functions/) to listen to changes to your particular collection and on create/update calculate the percentage and then use our official [JavaScript SDK](https://flamelink.github.io/flamelink/#/content?id=update) to write the updated entry back to the DB.

**Comment by rakipinsight** [comment]
Thanks for the info... @jperasmus
