### ISSUE TITLE
SDK - Async initialization

### ISSUE THREAD

**Issue by lkostrowski** [flamelink/flamelink#24]
Running `flamelink()` constructor is synchronous. I believe under the hood it has to run `firebase.auth()` or something similar to authorize the app, so the function is not aynchronous. 
I struggle to make this work in my Next.js setup. I need to be careful with client/ssr/server context and I faced problems that my constructed instance was not defined.
Shouldn't it return a promise?

**Comment by jperasmus** [comment]
You are correct that the `flamelink()` constructor is synchronous since it does not assume authentication. For instance, you might have a blog where the articles should be available to unauthenticated users on your website.

The `flamelink` SDK exposes the `authService` (and the other Firebase services) on the app instance for convenience. ie. `flamelinkApp.authService` is essentially the same as `firebaseApp.auth()`, so you can do logins like `flamelinkApp.authService.signInWithEmailAndPassword(email, password)`.

If you need authentication on your server, you can wrap the `flamelink` instantiation in a promise and listen to the auth state change before resolving. Something like this:

```
return new Promise((resolve, reject) => {
    const app = flamelink(/* config options here*/);
    app.authService.onAuthStateChanged(user => {
      // do something with user. Maybe query more flamelink data with app.content.get('products')
      resolve()
    })
})
```

**Comment by lkostrowski** [comment]
Hm I actually didn't mean user auth, but app-fb connection. How is the initialization of firebase synchronous, if it has to make a call to firebase somehow?

Anyways, I can always construct my firebaseApp independently and construct flamelink later ;)

**Comment by jperasmus** [comment]
Interestingly enough, there are no requests made when you initialize a firebase app. It is as soon as you get a reference to one of the services, like ‘firebase.db()’ that the websocket connection is opened.

**Comment by lkostrowski** [comment]
cool, makes sense! thanks dude
