### ISSUE TITLE
Users credentials was reseted at last update

### ISSUE THREAD

**Issue by imanbee** [flamelink/flamelink#31]
Hi! Thank you for such project! Yesterday I logged in Flamelink application (I am owner) and it told me that update is available, and I need to reload page to apply that update. Right after reloading page, I was logged out, and there was no luck to log in again. It told me that my account was disabled and I need to ask my system admin to fix it. Since this time, all users (which were located under`flamelink/users` in database) were not able to login, and they were not able to see any projects on Flamelink Dashboard, until I re-create them in Firebase Authentication. It was terrible situation, cause I was needed to remove them manually from database, and recreate each user.

What do you think, why such a situation appeared? Is there any chance it can appears in future?

**Comment by jperasmus** [comment]
Hi! Thanks for taking the time to add this issue. We are sorry that you had to experience this issue.

What happened here was that we identified a security issue with the users under `flamelink/users` where the `uid`'s were the same as the `uid`'s in the Firebase auth. This was because of an older bug we had in the app which was fixed a while ago already. With the latest release we fixed this security issue so that if the `uid`'s don't match up, we don't allow you to log into the app.

From what we've seen so far, this mostly affected a few users with projects that was created a while back and not recent ones. Out of interest, when did you first create your project and add your users?

We continuously try and improve the app, so it is definitely not our aim to ever put any user in a situation like this.

---

For other users that might stumble upon this issue, another way to fix this same problem is to first make sure that the uid's are the same in your database under `flamelink/users` as in your Firebase auth. If they are not the same, you can use the export/backup utility which will export your database in JSON format. Then you can fix up the `uid`s and import/restore your database again.

**Comment by imanbee** [comment]
Hi! Guys we stucked again with the same problem! How can we fix this? This time all flamelink users affected, including project owner. We just can't log in,
