### ISSUE TITLE
Items table dropped after trying to reorder

### ISSUE THREAD

**Issue by YuriiDunaev** [flamelink/flamelink#32]
1. Open flamelink project
2. Open "Items" project
3. Switch to list view (button on top-right) (check video)
4. Try to reorder
5. Save.

Result: web app crashes. Table contains single empty item
Expected: Table just saved.

https://drive.google.com/open?id=1O_PujQb1-2pUJGqKcT3wxr_vfHvATr6Q
https://drive.google.com/open?id=1NyQOjvHnRuuFbp4f-dRvtgCdRA_-e9qR

**Comment by dewetvdm** [comment]
Hi @YuriiDunaev what happens if you click on the parent item?

The parent item is collapsable (bad ui at the moment) but the subitems only show when you click on the parent item

example 

* Parent
** Sub 1
** Sub 2

when saving and returning it will only show 

* Parent and once you click on parent it will show 

* Parent
** Sub 1
** Sub 2
