### ISSUE TITLE
Error: permission_denied at /flamelink/environments/production/schemas

### ISSUE THREAD

**Issue by DigitalNomad2016** [flamelink/flamelink#45]
Hello, I tried googling everything but couldn't find a solution so....

Error: permission_denied at /flamelink/environments/production/schemas: Client doesn't have permission to access the desired data

I think it may have to do with firestore rules?  They are below:

`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}`

P.S.  Really diggin' Flamelink!

**Comment by jperasmus** [comment]
Hi @DigitalNomad2016 thanks for getting in touch.

When you added your Firebase project to Flamelink, did you add it as a Realtime DB or Cloud Firestore project? The rules are different for the different DBs.

To be sure, where are you seeing this error? Thinking about it now, it might be while using the SDK. If that is the case since our Cloud Firestore support is so new, the SDK does not yet work with it, but we are planning on updating the SDK soon.

**Comment by DigitalNomad2016** [comment]
Ahh yes I selected Firestore on sign-up.  Also in the project details, the Firestore button is highlighted.  

I'm using the npm package - flamelink.  Here's the relevant initialization code:

`import flamelink from 'flamelink'
const config = {
  apiKey: "NNNNNNNNNNNN",
  authDomain: "nnnnnn-nnnn.firebaseapp.com",
  databaseURL: "https://nnnnnn-nnnn.firebaseio.com",
  projectId: "nnnnnn-nnnn",
  storageBucket: "nnnnnn-nnnn.appspot.com",
  messagingSenderId: "nnnnnnn",
  env: 'production',
  locale: 'en-US'
}
export const FlameLink = flamelink(config)
`

`FlameLink.content.get('blog').then( blog =>
        console.log('All of your products:', blog)
      ).catch( e => console.log(e))`

**Comment by DigitalNomad2016** [comment]
So is it then not possible to use firestore with flamelink?

**Comment by jperasmus** [comment]
Yup, okay, that is what I expected 👍 

You have 2 options at this stage while we're working on implementing support for Firestore within our `flamelink` JavaScript SDK:

### Option 1
Switch to using the Realtime DB with Flamelink

### Option 2
Use the `firebase` SDK directly instead of our `flamelink` SDK

If you decide to go with Option 2, it is relatively easy to get this content out of Firestore. It will most likely look something like this:

```
import firebase from 'firebase/app'
import 'firebase/firestore'
// import other services you use

const config = {
  apiKey: "<API_KEY>",
  authDomain: "<PROJECT_ID>.firebaseapp.com",
  databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
  storageBucket: "<BUCKET>.appspot.com",
};

firebase.initializeApp(config);
const db = firebase.firestore();

db
  .collection('fl_content')
  .where('_fl_meta_.schema', '==', 'blog')
  .get()
  .then((querySnapshot) => {
    querySnapshot.forEach((doc) => {
        console.log(`${doc.id} => ${doc.data()}`);
    });
  })
  .catch(function(error) {
      console.log("Error getting documents: ", error);
  });
```

Since Flamelink stores all of the content in the Firestore DB, you can use the Firebase SDK to query your content. Our JavaScript SDK is a wrapper around the Firebase SDK that removes all of the "ugliness" for you.

**Comment by DigitalNomad2016** [comment]
Gotcha. And thanks!

**Comment by ribalnasr** [comment]
Hi!
storage.getURL(id) also doesn't work due to permissions issues, is it also because I'm using Firestore?
Thanks.

**Comment by ribalnasr** [comment]
Why is this issue closed? I say it's very important to update the sdk to support Firestore since Realtime Database is almost deprecated.
Should we expect any updates soon?

**Comment by jperasmus** [comment]
I've created a separate task now to track the Firestore feature.

**Comment by ribalnasr** [comment]
Great News!
Meanwhile, any code snippet for **.collection('fl_content').add({...})** in order to make sure content added from the frontend appears in the cms?

**Comment by DavidBegert** [comment]
Has this issue been fixed yet? I am getting this error trying to access firestore.

**Comment by jperasmus** [comment]
Hi @DavidBegert, this is not an issue that needs fixing. The error means that the Flamelink SDK is trying to read from the Firebase realtime database and permission is denied to do it. This can be because of different reasons: 
* you are actually planning on using Cloud Firestore. In that case, you should use the new SDK (repo is called flamelink-js-sdk here in Github)
* your realtime database permissions are blocking access. If you use the default permissions, reads and writes are only allowed for authenticated users. Depending on your use case, you either want to change your rules to allow unauthenticated access to certain data in your db, or you first want to authenticate the user before trying to access the data. This depends 100% on your use case and is the reason we can't give generic db rules that will work for everyone out of the box.

I hope this guides you in the right direction.
