### ISSUE TITLE
Confusing issue when using Flamelink with Nuxt.js

### ISSUE THREAD

**Issue by komiter** [flamelink/flamelink#59]
Hi!

I'm trying to use Flamelink with a static site generated by Nuxt.js and I'm running into a really confusing blocker that I really can't make any progress on.

When navigating to a page on the static site if the URL is missing a tailing slash i.e `/register` then I get the following error:

```Error: permission_denied at /flamelink/environments/production/schemas/constituencies: Client doesn't have permission to access the desired data.```

However, if I navigate to the URL with a trailing slash then there is no error.

I know there's a good chance this has nothing to do with Flamelink but just posting here to see if this is familiar to anyone.

Thanks!

**Comment by jperasmus** [comment]
Hi @komiter,

Apologies, I missed this issue. I'm not sure if you are still experiencing this. I can't tell you exactly what the problem is because it is definitely specific to your setup and your database permissions.

How are you initializing the flamelink app and set the queries? Is it using a URL param?
