### ISSUE TITLE
Getting started with the API

### ISSUE THREAD

**Issue by LightBen** [flamelink/flamelink#6]
Hi! I hope you won't mind asking for help I couldn't reach you, and because it's really new, there is nothing yet on the internet.

I get that in the console:

`Something went wrong while retrieving all the content. Details: Error: permission_denied at /flamelink/environments/production/schemas/blog-posts: Client doesn't have permission to access the desired data.`

I have in my index.html:

`
    <script src="https://www.gstatic.com/firebasejs/4.6.2/firebase.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flamelink/dist/flamelink.js"></script>
    <script src="bundle.js"></script>
</body>
`

Then, with webpack, I compile my scripts.js which gets into the bundle.js:

`
var firebase = require('firebase');
var flamelink = require('flamelink');

const firebaseConfig = {
    apiKey: "myApiKey",
    authDomain: "myDomain",
    databaseURL: "myDatabaseUrl",
    projectId: "myProjectId",
    storageBucket: "myStorageBucket",
    messagingSenderId: "MyId"
};

const firebaseApp = firebase.initializeApp(firebaseConfig);

const app = flamelink({ firebaseApp });
console.log('hello from scripts.js');
`

All is included in the network in the console, and I see my console log hello from scripts.js

What am I missing?

Thanks =)

**Comment by jperasmus** [comment]
Hi @LightBen 

Thanks for checking out our JavaScript SDK.

From what I can see, your code looks fine. It looks to me like your Firebase database permissions are not allowing access to the data. My first guess would be that the rules have "read" permissions only for authenticated users, meaning, only users that have already signed it can query the database. With the Firebase rules, you can be very specific and tie your DB access down to very specific access.

While you are still playing with the SDK, I would suggest you open up the "read" permissions so that the data can be queried by users not authenticated yet:

```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
    "flamelink": {
      ".read": true,
      ".write": "auth != null"
    }
  }
}
```

Also, take a look at [this issue](https://github.com/flamelink/flamelink/issues/1) for some more info regarding the permissions in general.

Let me know if that works for you.

**Comment by LightBen** [comment]
@jperasmus It's been 6 months, sorry, but I had some issues. I comment for future people reading this. It worked! Thanks!
