### ISSUE TITLE
Flamelink for android app

### ISSUE THREAD

**Issue by kaarens93** [flamelink/flamelink#87]
Hi, step 1 of adding a new project asks for Firebase Web Application Connection Code but since I'm creating an android app and not a web app, I don't see the connection code anywhere. I see there is a flamelink SDK for android (https://github.com/flamelink/flamelink-android-sdk) but I don't see how I'm able to get the connection code from that package.

Please advise, thanks!

**Comment by jperasmus** [comment]
Hi @kaarens93, thanks for reaching out.

The Firebase Web Application Connection Code is specifically to give the Flamelink web app the ability to connect to your Firebase project so that you can manage your content from within the app. You can still then use your Firebase project to build your Android app.

You can get the web app connection code from the Firebase console under the Project settings. It will look something like this:

```javascript
const firebaseConfig = {
  apiKey: "dsfasdfdsafa",
  authDomain: "my-project.firebaseapp.com",
  databaseURL: "https://my-project.firebaseio.com",
  projectId: "my-project",
  storageBucket: "my-project.appspot.com",
  messagingSenderId: "4567890987",
  appId: "1:45678909876:web:5bebbbf0cbb0254c"
};
```
